import { parseLineRecipeSnapshot } from "@/lib/order-types";
import {
  buildInventoryBalances,
  buildLineConsumptionRows,
  buildSemiProductRecipeMaps,
  splitImplicitProduction,
  type ConsumptionRow,
} from "@/lib/inventory-consumption";
import { computeMacCostForConsumptionRows } from "@/lib/mac-cogs";
import { buildPurchaseReceipt } from "@/lib/purchase-ledger-rebuild";

/**
 * Phase 1 of the owner-approved full-history rebuild plan
 * (C:\Users\Admin\.claude\plans\toasty-mapping-hollerith.md). Read-only.
 * Never writes anything -- produces a from-scratch, chronological
 * simulation of raw-ingredient inventory and cost_at_sale for the entire
 * order history, driven by sales-order data + the recipe effective at each
 * order's own timestamp, and purchase receipts replayed over time.
 *
 * Design (see the plan for the full reasoning): trusts PRODUCTION_CONSUME/
 * PRODUCTION_YIELD/STOCK_ADJUST as primitive facts, re-derives PO_RECEIPT
 * fresh from purchase_orders rather than trusting the stored copy, and
 * never trusts SALES_CONSUME-family rows -- those are exactly what this
 * engine exists to second-guess, regenerated by walking every order
 * chronologically against a balance this same engine builds forward in
 * time. This correctly nets a sale against real batch production (a real
 * PRODUCTION_YIELD genuinely raises the available semi-product balance) and
 * never depends on the old ledger's own possibly-corrupted running balance.
 *
 * Reuses lib/inventory-consumption.ts (recipe expansion, already handles
 * the "draw from semi-product balance first, explode only the shortfall"
 * mechanism) and lib/mac-cogs.ts (MAC replay) as-is -- no new recipe or
 * cost math here, only orchestration.
 */

export type RawOrder = {
  id: string;
  order_no?: string;
  status?: string;
  superseded_by?: string;
  created_at?: string;
};

export type RawLine = {
  id: string;
  order_id: string;
  qty?: string | number;
  recipe_snapshot_json?: string;
  modifiers_snapshot_json?: string;
  cost_at_sale?: string | number;
};

export type RawRecipe = {
  target_type?: string;
  target_id?: string;
  ingredients_json?: string;
  status?: string;
  start_date?: string | null;
  end_date?: string | null;
  created_at?: string;
};

export type RawSemiProduct = {
  id?: string;
  batch_yield?: string | number;
};

export type RawPurchaseOrder = {
  id: string;
  status?: string;
  transaction_date?: string;
  created_at?: string;
  subtotal_amount?: string | number;
  shipping_fee?: string | number;
  tax_amount?: string | number;
  voucher_amount?: string | number;
  discount_amount?: string | number;
};

export type RawPurchaseOrderLine = {
  id?: string;
  purchase_order_id?: string;
  purchased_item_id?: string;
  unit?: string;
  quantity?: string | number;
  subtotal?: string | number;
  conversion_id?: string;
};

export type RawPurchasedItem = {
  id: string;
  base_ingredient_id?: string;
};

export type RawConversion = {
  id: string;
  purchased_item_id?: string;
  purchased_unit?: string;
  conversion_rate?: string | number;
};

export type SimLedgerRow = {
  id: string;
  reference_id: string;
  item_reference: string;
  transaction_type: "PO_RECEIPT" | "PRODUCTION_CONSUME" | "PRODUCTION_YIELD" | "STOCK_ADJUST" | "SALES_CONSUME";
  quantity_change: number;
  unit_cost: number;
  created_at: string;
};

const TRUSTED_PRIMITIVE_TYPES = new Set(["PRODUCTION_CONSUME", "PRODUCTION_YIELD", "STOCK_ADJUST"]);

export function buildTrustedPrimitiveLedger(input: {
  purchaseOrders: RawPurchaseOrder[];
  purchaseOrderLines: RawPurchaseOrderLine[];
  purchasedItems: RawPurchasedItem[];
  conversions: RawConversion[];
  rawStockLedger: Array<{
    id?: string;
    reference_id?: string;
    item_reference?: string;
    transaction_type?: string;
    quantity_change?: string | number;
    unit_cost?: string | number;
    created_at?: string;
  }>;
}): { rows: SimLedgerRow[]; skippedPoReceipts: string[] } {
  const rows: SimLedgerRow[] = [];
  const skippedPoReceipts: string[] = [];

  const purchasedItemById = new Map(input.purchasedItems.map(item => [item.id, item]));
  const linesByPo = new Map<string, RawPurchaseOrderLine[]>();
  for (const line of input.purchaseOrderLines) {
    const poId = line.purchase_order_id || "";
    const arr = linesByPo.get(poId) || [];
    arr.push(line);
    linesByPo.set(poId, arr);
  }

  for (const po of input.purchaseOrders) {
    if (po.status !== "COMPLETED") continue;
    const effectiveDate = po.transaction_date || po.created_at || "";
    const lines = linesByPo.get(po.id) || [];
    for (const line of lines) {
      const item = purchasedItemById.get(line.purchased_item_id || "");
      if (!item) {
        skippedPoReceipts.push(`${po.id}/${line.id || "?"}: missing purchased item ${line.purchased_item_id}`);
        continue;
      }
      try {
        const receipt = buildPurchaseReceipt({ po, line, item, conversions: input.conversions });
        if (receipt.quantity_change <= 0) continue;
        rows.push({
          id: `TRUSTED-PO-${line.id}`,
          reference_id: po.id,
          item_reference: receipt.item_reference,
          transaction_type: "PO_RECEIPT",
          quantity_change: receipt.quantity_change,
          unit_cost: receipt.unit_cost,
          created_at: effectiveDate,
        });
      } catch (error) {
        skippedPoReceipts.push(`${po.id}/${line.id || "?"}: ${error instanceof Error ? error.message : String(error)}`);
      }
    }
  }

  for (const row of input.rawStockLedger) {
    if (!row.transaction_type || !TRUSTED_PRIMITIVE_TYPES.has(row.transaction_type)) continue;
    if (!row.item_reference || !row.created_at) continue;
    rows.push({
      id: row.id || `TRUSTED-${row.transaction_type}-${rows.length}`,
      reference_id: row.reference_id || "",
      item_reference: row.item_reference,
      transaction_type: row.transaction_type as SimLedgerRow["transaction_type"],
      quantity_change: Number(row.quantity_change) || 0,
      unit_cost: Number(row.unit_cost) || 0,
      created_at: row.created_at,
    });
  }

  return { rows, skippedPoReceipts };
}

export type LineRecomputeResult = {
  order_id: string;
  order_no: string;
  line_id: string;
  sale_time: string;
  stored_cost_at_sale: number;
  computed_cost_at_sale: number;
  consumption_rows: ConsumptionRow[];
};

export type ReplayResult = {
  lineResults: LineRecomputeResult[];
  computedLedger: SimLedgerRow[];
  errors: string[];
};

export function replayFullHistory(input: {
  orders: RawOrder[];
  lines: RawLine[];
  recipes: RawRecipe[];
  semiProducts: RawSemiProduct[];
  trustedPrimitives: SimLedgerRow[];
}): ReplayResult {
  const targetOrders = input.orders
    .filter(order => order.status === "COMPLETED" && !order.superseded_by)
    .sort((a, b) => new Date(a.created_at || 0).getTime() - new Date(b.created_at || 0).getTime());

  const linesByOrder = new Map<string, RawLine[]>();
  for (const line of input.lines) {
    const arr = linesByOrder.get(line.order_id) || [];
    arr.push(line);
    linesByOrder.set(line.order_id, arr);
  }

  const lineResults: LineRecomputeResult[] = [];
  const computedLedger: SimLedgerRow[] = [];
  const errors: string[] = [];

  for (const order of targetOrders) {
    const orderLines = linesByOrder.get(order.id) || [];
    if (orderLines.length === 0) continue;
    const orderTime = order.created_at || "";
    const orderTimeMs = new Date(orderTime).getTime();

    const pastLedger = [...input.trustedPrimitives, ...computedLedger].filter(row => {
      const rowMs = new Date(row.created_at).getTime();
      return rowMs <= orderTimeMs && row.reference_id !== order.id;
    });

    const balances = buildInventoryBalances(pastLedger, orderTime);
    const consumptionMaps = buildSemiProductRecipeMaps(input.recipes, input.semiProducts, orderTime);
    const implicitYields = new Map<string, number>();
    const orderRows: ConsumptionRow[] = [];

    for (const line of orderLines) {
      try {
        const lineRecipe = parseLineRecipeSnapshot(line.recipe_snapshot_json || "{}");
        const rows = buildLineConsumptionRows(
          lineRecipe,
          Number(line.qty) || 0,
          balances,
          consumptionMaps,
          implicitYields,
        );
        if (rows.length === 0) continue;

        const computedCost = computeMacCostForConsumptionRows(rows, pastLedger, orderTime, consumptionMaps);

        lineResults.push({
          order_id: order.id,
          order_no: order.order_no || order.id,
          line_id: line.id,
          sale_time: orderTime,
          stored_cost_at_sale: Number(line.cost_at_sale) || 0,
          computed_cost_at_sale: computedCost,
          consumption_rows: rows,
        });
        orderRows.push(...rows);
      } catch (error) {
        errors.push(`${order.order_no || order.id}/${line.id}: ${error instanceof Error ? error.message : String(error)}`);
      }
    }

    if (orderRows.length === 0) continue;

    const split = splitImplicitProduction(orderRows, implicitYields);
    let seq = 0;
    for (const row of split.saleRows) {
      computedLedger.push({
        id: `SIM-SALE-${order.id}-${seq++}`,
        reference_id: order.id,
        item_reference: row.item_reference,
        transaction_type: "SALES_CONSUME",
        quantity_change: -row.quantity,
        unit_cost: 0,
        created_at: orderTime,
      });
    }
    for (const row of split.productionConsumeRows) {
      computedLedger.push({
        id: `SIM-PC-${order.id}-${seq++}`,
        reference_id: order.id,
        item_reference: row.item_reference,
        transaction_type: "PRODUCTION_CONSUME",
        quantity_change: -row.quantity,
        unit_cost: 0,
        created_at: orderTime,
      });
    }
    for (const row of split.productionYieldRows) {
      computedLedger.push({
        id: `SIM-PY-${order.id}-${seq++}`,
        reference_id: order.id,
        item_reference: row.item_reference,
        transaction_type: "PRODUCTION_YIELD",
        quantity_change: row.quantity,
        unit_cost: 0,
        created_at: orderTime,
      });
    }
  }

  return { lineResults, computedLedger, errors };
}
