import * as fs from "node:fs";
import * as path from "node:path";
import { getSaigonDateStamp } from "../lib/script-cleanup-tools";
import { categorize, type Category } from "./generate-script-cleanup-plan-core";

/**
 * Phase 6.1 — Categorize all scripts and produce cleanup plan.
 *
 * Categories:
 *   KEEP_AUDIT             — ongoing audit scripts referenced by roadmap
 *   KEEP_RUNBOOK           — reusable operations (reprocess, restore, reaudit)
 *   KEEP_MIGRATION_HISTORY — one-time migrations preserved as historical record
 *   DELETE_ONE_OFF         — investigative/fix scripts with no current value
 *   ARCHIVE_DOC_ONLY       — scripts that already served their purpose; move to docs/ for reference
 */

interface ScriptInfo {
  name: string;
  size: number;
  category: Category;
  reason: string;
}

function main() {
  const scriptsDir = path.resolve(__dirname);
  const files = fs.readdirSync(scriptsDir).filter(f => f.endsWith(".ts") || f.endsWith(".js"));

  const infos: ScriptInfo[] = files.map(name => {
    const stat = fs.statSync(path.join(scriptsDir, name));
    const { category, reason } = categorize(name);
    return { name, size: stat.size, category, reason };
  });

  const byCategory = new Map<Category, ScriptInfo[]>();
  for (const info of infos) {
    const rows = byCategory.get(info.category) || [];
    rows.push(info);
    byCategory.set(info.category, rows);
  }

  const today = getSaigonDateStamp();
  let report = `# Script Cleanup Plan\n\nDate: ${today}\nGenerated by: scripts/generate-script-cleanup-plan.ts\n\n`;
  report += `## Summary\n\n`;
  report += `Total scripts: ${infos.length}\n\n`;
  report += `| Category | Count |\n`;
  report += `|----------|-------|\n`;
  for (const cat of ["KEEP_AUDIT", "KEEP_RUNBOOK", "KEEP_MIGRATION_HISTORY", "ARCHIVE_DOC_ONLY", "DELETE_ONE_OFF"] as Category[]) {
    report += `| ${cat} | ${(byCategory.get(cat) || []).length} |\n`;
  }

  report += `\n## Category definitions\n\n`;
  report += `- **KEEP_AUDIT**: ongoing audit scripts referenced by roadmap. Re-run any time.\n`;
  report += `- **KEEP_RUNBOOK**: reusable operations (reprocess, restore, init). Needed for future ops.\n`;
  report += `- **KEEP_MIGRATION_HISTORY**: one-time migration scripts. Keep as historical record/audit trail.\n`;
  report += `- **ARCHIVE_DOC_ONLY**: one-off data fixes already applied. Move to docs/ for reference, not for re-run.\n`;
  report += `- **DELETE_ONE_OFF**: investigation/test scripts with no current value.\n`;

  for (const cat of ["KEEP_AUDIT", "KEEP_RUNBOOK", "KEEP_MIGRATION_HISTORY", "ARCHIVE_DOC_ONLY", "DELETE_ONE_OFF"] as Category[]) {
    const rows = byCategory.get(cat) || [];
    if (rows.length === 0) continue;
    report += `\n## ${cat} (${rows.length})\n\n`;
    for (const r of rows.sort((a, b) => a.name.localeCompare(b.name))) {
      report += `- \`${r.name}\` — ${r.reason}\n`;
    }
  }

  report += `\n## Recommended actions\n\n`;
  report += `1. **KEEP_AUDIT** (do nothing) — these scripts form the audit baseline.\n`;
  report += `2. **KEEP_RUNBOOK** (do nothing) — reusable for future operations.\n`;
  report += `3. **KEEP_MIGRATION_HISTORY** (do nothing) — preserve as audit trail of how V2 data was built.\n`;
  report += `4. **ARCHIVE_DOC_ONLY** — consider moving to \`docs/audits/archive-scripts.md\` (referenced as listing only, not executed).\n`;
  report += `5. **DELETE_ONE_OFF** — review each before deletion; delete in a separate commit with the cleanup-plan as reference.\n`;

  const outputPath = path.resolve(__dirname, "..", "docs", "audits", "script-cleanup-plan.md");
  fs.writeFileSync(outputPath, report, "utf8");
  console.log(`Wrote ${outputPath}`);
  console.log(`Total scripts: ${infos.length}`);
  for (const [cat, rows] of byCategory.entries()) {
    console.log(`  ${cat}: ${rows.length}`);
  }
}

main();
