import * as fs from "node:fs";
import * as path from "node:path";
import { getSaigonDateStamp } from "../lib/script-cleanup-tools";

/**
 * Phase 6.1 — Categorize all scripts and produce cleanup plan.
 *
 * Categories:
 *   KEEP_AUDIT             — ongoing audit scripts referenced by roadmap
 *   KEEP_RUNBOOK           — reusable operations (reprocess, restore, reaudit)
 *   KEEP_MIGRATION_HISTORY — one-time migrations preserved as historical record
 *   DELETE_ONE_OFF         — investigative/fix scripts with no current value
 *   ARCHIVE_DOC_ONLY       — scripts that already served their purpose; move to docs/ for reference
 */

type Category = "KEEP_AUDIT" | "KEEP_RUNBOOK" | "KEEP_MIGRATION_HISTORY" | "DELETE_ONE_OFF" | "ARCHIVE_DOC_ONLY";

interface ScriptInfo {
  name: string;
  size: number;
  category: Category;
  reason: string;
}

const AUDIT_PREFIXES = ["audit-", "check-"];
const RUNBOOK_KEYWORDS = ["reprocess", "restore", "reaudit", "rename-v1", "reset-v2", "init-", "standalone-sheets-utils", "batch-sheets-utils", "create-v2-sheets", "backup-v1", "reconcile-v1-v2", "reconcile-migrated"];
const MIGRATION_KEYWORDS = ["migrate", "remigrate", "batch-migrate", "re-migrate"];
const ONE_OFF_KEYWORDS = ["investigate", "fix-", "find-", "recover-", "verify-", "test-", "debug-", "check-", "spot", "diagnose", "diff-", "classify-"];
const ARCHIVE_KEYWORDS = ["add-column", "add-snapshot", "add-line", "add-transaction", "add-unit", "apply-", "backfill-", "clear-", "cleanup-", "delete-", "patch", "rename", "update-btp", "update-po-headers", "update-inventory", "zero-out"];

function categorize(name: string): { category: Category; reason: string } {
  // Specific recent additions for Dao Mieng work
  if (name === "audit-dao-mieng-report-cogs.ts" || name === "verify-cogs-allocation-impact.ts" || name === "spotcheck-mod004.ts") {
    return { category: "ARCHIVE_DOC_ONLY", reason: "Dao Mieng investigation scripts, kept as reference; bug now fixed" };
  }
  if (name === "audit-negative-periods-classification.ts" || name === "audit-void-orders.ts" || name === "audit-stock-ledger-schema.ts" || name === "audit-stock-adjustments.ts" || name === "audit-order-total-consistency.ts" || name === "audit-po-save-ledger.ts") {
    return { category: "KEEP_AUDIT", reason: "Phase 2-4 audit scripts from Claude code session" };
  }

  if (AUDIT_PREFIXES.some(p => name.startsWith(p))) {
    return { category: "KEEP_AUDIT", reason: "Audit script — referenced in roadmap" };
  }

  for (const keyword of RUNBOOK_KEYWORDS) {
    if (name.includes(keyword)) {
      return { category: "KEEP_RUNBOOK", reason: `Reusable operation (${keyword})` };
    }
  }

  for (const keyword of MIGRATION_KEYWORDS) {
    if (name.includes(keyword)) {
      return { category: "KEEP_MIGRATION_HISTORY", reason: "Migration script preserved as historical record" };
    }
  }

  for (const keyword of ONE_OFF_KEYWORDS) {
    if (name.includes(keyword)) {
      return { category: "DELETE_ONE_OFF", reason: `One-off investigation/fix (${keyword})` };
    }
  }

  for (const keyword of ARCHIVE_KEYWORDS) {
    if (name.includes(keyword)) {
      return { category: "ARCHIVE_DOC_ONLY", reason: `One-off data fix (${keyword}) — keep for audit trail, not for re-run` };
    }
  }

  return { category: "DELETE_ONE_OFF", reason: "Unclassified — default to one-off" };
}

function main() {
  const scriptsDir = path.resolve(__dirname);
  const files = fs.readdirSync(scriptsDir).filter(f => f.endsWith(".ts") || f.endsWith(".js"));

  const infos: ScriptInfo[] = files.map(name => {
    const stat = fs.statSync(path.join(scriptsDir, name));
    const { category, reason } = categorize(name);
    return { name, size: stat.size, category, reason };
  });

  const byCategory = new Map<Category, ScriptInfo[]>();
  for (const info of infos) {
    const rows = byCategory.get(info.category) || [];
    rows.push(info);
    byCategory.set(info.category, rows);
  }

  const today = getSaigonDateStamp();
  let report = `# Script Cleanup Plan\n\nDate: ${today}\nGenerated by: scripts/generate-script-cleanup-plan.ts\n\n`;
  report += `## Summary\n\n`;
  report += `Total scripts: ${infos.length}\n\n`;
  report += `| Category | Count |\n`;
  report += `|----------|-------|\n`;
  for (const cat of ["KEEP_AUDIT", "KEEP_RUNBOOK", "KEEP_MIGRATION_HISTORY", "ARCHIVE_DOC_ONLY", "DELETE_ONE_OFF"] as Category[]) {
    report += `| ${cat} | ${(byCategory.get(cat) || []).length} |\n`;
  }

  report += `\n## Category definitions\n\n`;
  report += `- **KEEP_AUDIT**: ongoing audit scripts referenced by roadmap. Re-run any time.\n`;
  report += `- **KEEP_RUNBOOK**: reusable operations (reprocess, restore, init). Needed for future ops.\n`;
  report += `- **KEEP_MIGRATION_HISTORY**: one-time migration scripts. Keep as historical record/audit trail.\n`;
  report += `- **ARCHIVE_DOC_ONLY**: one-off data fixes already applied. Move to docs/ for reference, not for re-run.\n`;
  report += `- **DELETE_ONE_OFF**: investigation/test scripts with no current value.\n`;

  for (const cat of ["KEEP_AUDIT", "KEEP_RUNBOOK", "KEEP_MIGRATION_HISTORY", "ARCHIVE_DOC_ONLY", "DELETE_ONE_OFF"] as Category[]) {
    const rows = byCategory.get(cat) || [];
    if (rows.length === 0) continue;
    report += `\n## ${cat} (${rows.length})\n\n`;
    for (const r of rows.sort((a, b) => a.name.localeCompare(b.name))) {
      report += `- \`${r.name}\` — ${r.reason}\n`;
    }
  }

  report += `\n## Recommended actions\n\n`;
  report += `1. **KEEP_AUDIT** (do nothing) — these scripts form the audit baseline.\n`;
  report += `2. **KEEP_RUNBOOK** (do nothing) — reusable for future operations.\n`;
  report += `3. **KEEP_MIGRATION_HISTORY** (do nothing) — preserve as audit trail of how V2 data was built.\n`;
  report += `4. **ARCHIVE_DOC_ONLY** — consider moving to \`docs/audits/archive-scripts.md\` (referenced as listing only, not executed).\n`;
  report += `5. **DELETE_ONE_OFF** — review each before deletion; delete in a separate commit with the cleanup-plan as reference.\n`;

  const outputPath = path.resolve(__dirname, "..", "docs", "audits", "script-cleanup-plan.md");
  fs.writeFileSync(outputPath, report, "utf8");
  console.log(`Wrote ${outputPath}`);
  console.log(`Total scripts: ${infos.length}`);
  for (const [cat, rows] of byCategory.entries()) {
    console.log(`  ${cat}: ${rows.length}`);
  }
}

main();
