/**
 * Phase 6.2: Verify DELETE_ONE_OFF script safety.
 *
 * For each script in DELETE_ONE_OFF category (read live from script-cleanup-plan.md,
 * not hardcoded -- the plan is regenerated periodically and the list drifts):
 * 1. Check if file still exists.
 * 2. Grep codebase for references (excluding the script itself + cleanup plan + tracking docs).
 * 3. Flag if referenced anywhere meaningful.
 *
 * Output: docs/audits/<today>-script-deletion-verification.md
 *
 * Claude code -- Phase 6.2 read-only audit.
 */

import * as fs from "node:fs";
import * as path from "node:path";
import {
  getSaigonDateStamp,
  hasScriptReference,
  parseDeleteOneOffList,
} from "../lib/script-cleanup-tools";

const REPO_ROOT = process.cwd();
const SCRIPTS_DIR = path.join(REPO_ROOT, "scripts");

function loadDeleteOneOffList(): string[] {
  const planPath = path.join(REPO_ROOT, "docs/audits/script-cleanup-plan.md");
  return parseDeleteOneOffList(fs.readFileSync(planPath, "utf8"));
}

const DELETE_ONE_OFF = loadDeleteOneOffList();

function walkDir(dir: string, results: string[] = []): string[] {
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    if (entry.name === "node_modules" || entry.name === ".git" || entry.name === ".next") continue;
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      walkDir(fullPath, results);
    } else if (entry.isFile()) {
      results.push(fullPath);
    }
  }
  return results;
}

function findReferences(scriptName: string): string[] {
  const refs: string[] = [];
  const allFiles = walkDir(REPO_ROOT);
  const excludePatterns = [
    /^scripts\/verify-delete-candidates\.ts$/,
    /^scripts\/script-name-placeholder$/, // never match
  ];
  for (const file of allFiles) {
    const relPath = path.relative(REPO_ROOT, file).split(path.sep).join("/");
    if (relPath === `scripts/${scriptName}`) continue;
    if (excludePatterns.some(p => p.test(relPath))) continue;
    // Skip noise: build cache, lock files, audit JSONs, generated reports.
    if (relPath === "tsconfig.tsbuildinfo") continue;
    if (relPath.endsWith(".lock")) continue;
    if (relPath === "package-lock.json") continue;
    if (relPath === "docs/audits/sheet-usage-report.json") continue;
    if (relPath === "docs/audits/2026-06-26-folder-cleanup-proposal.md") continue;
    if (relPath === "docs/audits/script-cleanup-plan.md") continue;
    if (/^docs\/audits\/\d{4}-\d{2}-\d{2}-script-deletion-verification\.md$/.test(relPath)) continue;
    if (relPath === "DEVELOPMENT-TRACKING.md") continue;
    if (relPath === "docs/audits/codex-handoff-2026-06-25.md") continue;
    if (relPath === "docs/audits/2026-06-25-full-system-audit-roadmap.md") continue;

    try {
      const content = fs.readFileSync(file, "utf8");
      if (hasScriptReference(content, scriptName)) {
        refs.push(relPath);
      }
    } catch {
      // Binary file, skip.
    }
  }
  return refs;
}

function main() {
  const today = getSaigonDateStamp();
  const lines: string[] = [];
  lines.push("# Phase 6.2 — Script Deletion Verification");
  lines.push("");
  lines.push(`Date: ${today}`);
  lines.push(`Generated by: scripts/verify-delete-candidates.ts`);
  lines.push("");
  lines.push(`Audited ${DELETE_ONE_OFF.length} DELETE_ONE_OFF scripts.`);
  lines.push("");

  const safe: string[] = [];
  const referenced: Array<{ script: string; refs: string[] }> = [];
  const missing: string[] = [];

  for (const script of DELETE_ONE_OFF) {
    const fullPath = path.join(SCRIPTS_DIR, script);
    if (!fs.existsSync(fullPath)) {
      missing.push(script);
      continue;
    }
    const refs = findReferences(script);
    if (refs.length === 0) {
      safe.push(script);
    } else {
      referenced.push({ script, refs });
    }
  }

  lines.push(`## Summary`);
  lines.push("");
  lines.push(`| Status | Count |`);
  lines.push(`|---|---|`);
  lines.push(`| Safe to delete (no references) | ${safe.length} |`);
  lines.push(`| Referenced elsewhere (review needed) | ${referenced.length} |`);
  lines.push(`| Already deleted (file not found) | ${missing.length} |`);
  lines.push("");

  lines.push(`## Safe to delete (${safe.length})`);
  lines.push("");
  for (const s of safe) {
    lines.push(`- \`${s}\``);
  }
  lines.push("");

  if (referenced.length > 0) {
    lines.push(`## Referenced elsewhere — REVIEW NEEDED (${referenced.length})`);
    lines.push("");
    for (const { script, refs } of referenced) {
      lines.push(`### \`${script}\``);
      for (const r of refs) {
        lines.push(`- ${r}`);
      }
      lines.push("");
    }
  }

  if (missing.length > 0) {
    lines.push(`## Already deleted (${missing.length})`);
    lines.push("");
    for (const s of missing) {
      lines.push(`- \`${s}\``);
    }
    lines.push("");
  }

  const outputPath = path.join(REPO_ROOT, `docs/audits/${today}-script-deletion-verification.md`);
  fs.writeFileSync(outputPath, lines.join("\n"));
  console.log(`Output: ${path.relative(REPO_ROOT, outputPath)}`);
  console.log(`Safe: ${safe.length}, Referenced: ${referenced.length}, Missing: ${missing.length}`);
}

main();
